Improve github functionality, add conditionals

diff --git a/install_script b/install_script
--- a/install_script
+++ b/install_script
@@ -1,43 +1,54 @@
 #!/bin/bash
 
 # OPTIONS:
-# -p (--poweroff)   :  Poweroff after imaging. 
-# -i (--info)       :  Print system info.
 # -t (--test)       :  Do not make changes to drives.
-# -u (--usb)        :  Use USB image instead of final image.
-# -g (--git)        :  Check for updates before running. ASSUMED INTERNET CONNECTION!
+# -u (--usb)        :  Use USB image instead of final image; do not print system info
+# -g (--git)        :  Check for updates before running.
 
 # exit if any command fails
 set -e
-
-# update if requested
-if [[ "$@" == *"-g"* ]]; then
-    cd /install/PCF
-    if [[ "$( echo $(sudo git pull))" != *"up-to-date"* ]]; then
-        sudo ./install_script $@
-        exit 1
-    fi
-fi
 
 # define text types
 bold=$(tput bold)
 normal=$(tput sgr0)
 
-# retrieve system info
-cpu="$(cat /proc/cpuinfo | grep 'name' | uniq )"
-cpu=${cpu%CPU*}
-cpu=${cpu##*: }
-mem="$(cat /proc/meminfo | grep 'MemTotal')"
-mem=${mem% kB*}
-mem=${mem##*:}
-mem="$( echo "scale=1; $mem / 1024 / 1024" | bc -l)"
-# mdy=$(date +%m-%d-%Y)
-version=$(ls /install/PCF | grep 'v')
-[[ "$@" == *"-u"* ]] || IFS=' ' read -r -a images <<< "$(echo $(ls /install | grep 'pcf'))"
-[[ "$@" == *"-u"* ]] && IFS=' ' read -r -a images <<< "$(echo $(ls /install | grep 'usb'))"
+# update if requested
+if [[ "$@" == *"-g"* ]]; then
+    cd /install/PCF
+    git_output="$( echo $(sudo git pull))"
+    if [[ git_output == *"up-to-date"* ]]
+    then
+        printf "Script is up to date!"
+    elif [[ git_output == *"Could not resolve hostname github.com"* ]]; then
+        printf "No internet connection; cannot update."
+    else 
+        sudo ./install_script $@
+        exit 1
+    fi
+fi
 
-# print system info
-[[ "$@" == *"-i"* ]] && printf "\nVers:\t${bold}$version${normal}\nCPU:\t${bold}$cpu${normal}\nMEM:\t${bold}$mem GiB${normal}\n\n"
+if [[ "$@" == *"-u"* ]]
+then    # we are imaging a USB
+    IFS=' ' read -r -a images <<< "$(echo $(ls /install | grep 'usb'))"
+
+else    # we are imaging a drive
+    # retrieve system info
+    IFS=' ' read -r -a images <<< "$(echo $(ls /install | grep 'pcf'))"
+    image="${images[-1]}"
+    cpu="$(cat /proc/cpuinfo | grep 'name' | uniq )"
+    cpu=${cpu%CPU*}
+    cpu=${cpu##*: }
+    mem="$(cat /proc/meminfo | grep 'MemTotal')"
+    mem=${mem% kB*}
+    mem=${mem##*:}
+    mem="$( echo "scale=1; $mem / 1024 / 1024" | bc -l)"
+    version=$(ls /install/PCF | grep 'v')
+
+    printf "\nVers:\t${bold}$version${normal}\nCPU:\t${bold}$cpu${normal}\nMEM:\t${bold}$mem GiB${normal}\n\n"
+
+    [[ $(echo "$mem < 1.8" | bc -l ) -eq "1" ]] && printf "Memory is < 2Gib, exiting.\n" && exit 1
+
+fi
 
 # retrieve volume and partition info
 volumeInfo=( $(lsblk -b -n -o name,size,mountpoint | tr '\n' ' ') )
@@ -54,7 +65,6 @@ done
 
 # exit conditions
 [[ ${#drives[@]} -eq 0 ]] && (printf "No drives found, exiting.\n" && exit 1)
-[[ $(echo "$mem < 1.8" | bc -l ) -eq "1" ]] && printf "Memory is < 2Gib, exiting.\n" && exit 1
 
 # print summary
 for i in ${!drives[@]}; do
@@ -65,10 +75,10 @@ done
 [[ "$@" == *"-t"* ]] && exit 1
 
 for i in ${!drives[@]}; do
-    printf "\nBEGINNING DRIVE #"$(echo "$i + 1" | bc )"...\n"
+    [[ "$@" == *"-u"* ]] && printf "\nBEGINNING DRIVE #"$(echo "$i + 1" | bc )"...\n"
 
     # apply image
-    pv </install/"${images[-1]}" >/dev/"${drives[$i]}"
+    pv </install/"$image" >/dev/"${drives[$i]}"
 
     # grow partition
     sudo parted /dev/"${drives[$i]}" resizepart 1 "${sizes[$i]}"G
@@ -77,10 +87,10 @@ for i in ${!drives[@]}; do
     sudo e2fsck -f /dev/"${drives[$i]}"1
     sudo resize2fs -p /dev/"${drives[$i]}"1
 
-    printf "DRIVE COMPLETE.\n"
+    [[ "$@" == *"-u"* ]] && printf "DRIVE COMPLETE.\n"
 done
 
 (speaker-test -t sine -f 800 )& pid=$! ; sleep 0.3s ; kill -9 $pid
 
-# poweroff if requested
-[[ "$@" == *"-p"* ]] && poweroff
+# poweroff if necessary
+[[ "$@" == *"-u"* ]] || poweroff
