New version system

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# exit if any command fails
+set -e
+
 # define text types
 bold=$(tput bold)
 normal=$(tput sgr0)
@@ -8,14 +11,15 @@ normal=$(tput sgr0)
 cpu="$(cat /proc/cpuinfo | grep 'name' | uniq )"
 cpu=${cpu%CPU*}
 cpu=${cpu##*: }
+cpu="CPU: ${bold}$cpu${normal}"
 mem="$(cat /proc/meminfo | grep 'MemTotal')"
 mem=${mem% kB*}
 mem=${mem##*:}
-mem="$( echo "scale=1; $mem / 1024 / 1024" | bc -l) GiB"
+mem="$( echo "scale=1; $mem / 1024 / 1024" | bc -l)"
+mem="MEM: ${bold}$mem GiB${normal}"
 
-printf "\nCPU: ${bold}$cpu${normal}"
-printf "\nMEM: ${bold}$mem${normal}\n\n"
-
+printf "\n$cpu"
+printf "\n$mem GiB\n\n"
 
 # retrieve and parse volumes and partitions
 IFS=' ' read -r -a array <<< "$(echo $(lsblk -b -n -o name,size,mountpoint) | tr -d '\n')"
@@ -33,17 +37,28 @@ target_size="$( echo "${array["$( echo "$i + 1" | bc )"]} / 1024^3 - 5" | bc )"
 
 printf "${bold}/dev/"$target_volume"1${normal} will be imaged and resized to ${bold}$target_size GiB${normal}.\n\n"
 
+# allow user to safely kill process
+for((j=5;j>0;--j)) do
+	printf "\rStarting process in $j... (CTRL+C to exit)"
+	sleep 1
+done
+printf "\r"
+
 [[ "$1" == *"-t"* ]] && exit 1
 
-# apply image, create sdx1
+# apply image
 pv </install/pcf.img >/dev/"$target_volume"
 
 # grow partition
 sudo parted /dev/"$target_volume" resizepart 1 "$target_size"G
 
-# resize filesystem to match partition
+# grow filesystem to match partition
 sudo e2fsck -f /dev/"$target_volume"1
 sudo resize2fs -p /dev/"$target_volume"1
+
+# create info file on new image
+sudo mount "/dev/"$target_volume"1" /mnt
+sudo printf "$cpu\n$mem\n" > /mnt/home/pcfit/Documents/sys_info
 
 # reboot into new image
 (speaker-test -t sine -f 800 )& pid=$! ; sleep 0.3s ; kill -9 $pid
